[build]
builder = "dockerfile"

[deploy]
# Отключаем healthcheck, так как бот использует polling
healthcheckPath = ""
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services.main]
processes = ["python", "app.py"]